pinry/core/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from tastypie.api import Api

from .api import ImageResource, ThumbnailResource, PinResource, UserResource
from .views import CreateImage


v1_api = Api(api_name='v1')
v1_api.register(ImageResource())
v1_api.register(ThumbnailResource())
v1_api.register(PinResource())
v1_api.register(UserResource())


urlpatterns = patterns('',
    url(r'^api/', include(v1_api.urls, namespace='api')),

    url(r'^pins/pin-form/$', TemplateView.as_view(template_name='core/pin_form.html'),
        name='pin-form'),
    url(r'^pins/create-image/$', CreateImage.as_view(), name='create-image'),

    url(r'^pins/tag/(?P<tag>(\w|-)+)/$', TemplateView.as_view(template_name='core/pins.html'),
        name='tag-pins'),
    url(r'^pins/user/(?P<user>(\w|-)+)/$', TemplateView.as_view(template_name='core/pins.html'),
        name='user-pins'),
    url(r'^$', TemplateView.as_view(template_name='core/pins.html'),
        name='recent-pins'),
)

pinry/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = patterns('',
                       url(r'', include('pinry.core.urls', namespace='core')),
                       url(r'', include('pinry.users.urls', namespace='users')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinry/users/urls.py
from django.conf.urls import patterns, url

from .views import CreateUser

urlpatterns = patterns('',
    url(r'^private/$', 'pinry.users.views.private', name='private'),
    url(r'^register/$', CreateUser.as_view(), name='register'),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', 'pinry.users.views.logout_user', name='logout'),
)

pinry/core/models.py
import urllib2
from cStringIO import StringIO

from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models

from django_images.models import Image as BaseImage
from taggit.managers import TaggableManager

from ..users.models import User


class ImageManager(models.Manager):
    # FIXME: Move this into an asynchronous task
    def create_for_url(self, url):
        file_name = url.split("/")[-1]
        buf = StringIO()
        buf.write(urllib2.urlopen(url).read())
        obj = InMemoryUploadedFile(buf, 'image', file_name, None, buf.tell(), None)
        return Image.objects.create(image=obj)


class Image(BaseImage):
    objects = ImageManager()

    class Meta:
        proxy = True


class Pin(models.Model):
    submitter = models.ForeignKey(User)
    url = models.URLField(null=True)
    origin = models.URLField(null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ForeignKey(Image, related_name='pin')
    published = models.DateTimeField(auto_now_add=True)
    tags = TaggableManager()

    def __unicode__(self):
        return self.url

pinry/users/models.py
import hashlib

from django.contrib.auth.models import User as BaseUser


class User(BaseUser):
    @property
    def gravatar(self):
        return hashlib.md5(self.email).hexdigest()

    class Meta:
        proxy = True

pinry/core/forms.py
from django import forms

from django_images.models import Image


FIELD_NAME_MAPPING = {
    'image': 'qqfile',
}


class ImageForm(forms.ModelForm):
    def add_prefix(self, field_name):
        field_name = FIELD_NAME_MAPPING.get(field_name, field_name)
        return super(ImageForm, self).add_prefix(field_name)

    class Meta:
        model = Image
        fields = ('image',)

pinry/users/forms.py
from django import forms
from django.utils.translation import ugettext, ugettext_lazy as _
from django.contrib.auth.models import User


class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username,
    email, and password.
    """
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
    }
    username = forms.RegexField(label=_("Username"), max_length=30,
        regex=r'^[\w-]+$')
    password = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "email")

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User._default_manager.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

pinry/core/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import CreateView
from django_images.models import Image

from braces.views import JSONResponseMixin, LoginRequiredMixin

from .forms import ImageForm


class CreateImage(JSONResponseMixin, LoginRequiredMixin, CreateView):
    template_name = None  # JavaScript-only view
    model = Image
    form_class = ImageForm

    def get(self, request, *args, **kwargs):
        if not request.is_ajax():
            return HttpResponseRedirect(reverse('core:recent-pins'))
        return super(CreateImage, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        image = form.save()
        return self.render_json_response({
            'success': {
                'id': image.id
            }
        })

    def form_invalid(self, form):
        return self.render_json_response({'error': form.errors})

pinry/users/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Permission
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.utils.functional import lazy
from django.views.generic import CreateView

from .forms import UserCreationForm
from pinry.users.models import User


reverse_lazy = lambda name=None, *args: lazy(reverse, str)(name, args=args)


class CreateUser(CreateView):
    template_name = 'users/register.html'
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('core:recent-pins')

    def get(self, request, *args, **kwargs):
        if not settings.ALLOW_NEW_REGISTRATIONS:
            messages.error(request, "The admin of this service is not allowing new registrations.")
            return HttpResponseRedirect(reverse('core:recent-pins'))
        return super(CreateUser, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        redirect = super(CreateUser, self).form_valid(form)
        permissions = Permission.objects.filter(codename__in=['add_pin', 'add_image'])
        user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])
        user.user_permissions = permissions
        login(self.request, user)
        return redirect


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, 'You have successfully logged out.')
    return HttpResponseRedirect(reverse('core:recent-pins'))


def private(request):
    return TemplateResponse(request, 'users/private.html', None)

pinry/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>

        <!--  ___                     ___           ___                 
             /  /\      ___          /__/\         /  /\          ___   
            /  /::\    /  /\         \  \:\       /  /::\        /__/|  
           /  /:/\:\  /  /:/          \  \:\     /  /:/\:\      |  |:|  
          /  /:/~/:/ /__/::\      _____\__\:\   /  /:/~/:/      |  |:|  
         /__/:/ /:/  \__\/\:\__  /__/::::::::\ /__/:/ /:/___  __|__|:|  
         \  \:\/:/      \  \:\/\ \  \:\~~\~~\/ \  \:\/:::::/ /__/::::\  
          \  \::/        \__\::/  \  \:\  ~~~   \  \::/~~~~     ~\~~\:\ 
           \  \:\        /__/:/    \  \:\        \  \:\           \  \:\
            \  \:\       \__\/      \  \:\        \  \:\           \__\/
             \__\/                   \__\/         \__\/             -->

        <title>{% block title %}{{ SITE_NAME }}{% endblock %}</title>

        <!-- CSS -->
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Monoton"/>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.0/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/file-uploader/3.1.1/fineuploader.css"/>
        <link rel="stylesheet" href="{{ STATIC_URL }}css/messages.css"/>
        <link rel="stylesheet" href="{{ STATIC_URL }}css/lightbox.css"/>
        <link rel="stylesheet" href="{{ STATIC_URL }}css/pinry.css"/>
        {% block extra_css %}{% endblock %}
        <!-- End CSS -->

        <!-- Start JavaScript Variables -->
        <script>
        var apiLimitPerPage = {{ API_LIMIT_PER_PAGE }},
            currentUser = {
                id: "{{ user.id }}",
                username: "{{ user.username }}",
                gravatar: "{{ user.gravatar }}"
            },
            tagFilter = "{{ request.resolver_match.kwargs.tag }}",
            userFilter = "{{ request.resolver_match.kwargs.user }}";
        </script>
        <!-- End JavaScript Variables -->
    </head>

    <body>
        <!-- Navigation -->
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <a href="{% url 'core:recent-pins' %}" class="brand pull-left">{{ SITE_NAME }}</a>
                <ul class="nav pull-right">
                {% if user.is_authenticated %}
                    <li>{% include "includes/bookmarklet_link.html" %}</li>
                    <li><a onclick="pinForm()">New Pin</a></li>
                    <li><a href="{% url 'users:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'users:login' %}">Login</a></li>
                    <li><a href="{% url 'users:register' %}">Register</a></li>
                {% endif %}
                </ul>
            </div>
        </div>
        <!-- End Navigation -->

        <!-- Content -->
        {% block yield %}{% endblock %}
        <!-- End Content -->

        <!-- Messages -->
        {% include "includes/messages.html" %}
        <!-- End Messages -->

        <!-- Templates -->
        {% include "includes/lightbox.html" %}
        {% include "includes/pins.html" %}
        {% include "includes/pin_form.html" %}
        {% block extra_templates %}{% endblock %}
        <!-- End Templates -->

        <!-- JavaScript -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.0/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.0.0-rc.3/handlebars.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/file-uploader/3.1.1/jquery.fineuploader.min.js"></script>
        <script src="{{ STATIC_URL }}js/helpers.js"></script>
        <script src="{{ STATIC_URL }}js/messages.js"></script>
        <script src="{{ STATIC_URL }}js/lightbox.js"></script>
        <script src="{{ STATIC_URL }}js/pinry.js"></script>
        <script src="{{ STATIC_URL }}js/pin-form.js"></script>
        {% block extra_js %}{% endblock %}
        <!-- End JavaScript -->
    </body>
</html>

pinry/templates/core/pin_form.html
{% extends "base.html" %}

{% block title %}Pin Form{% endblock %}

{% block yield %}
    <div id="display-pin-form"></div>
{% endblock %}

pinry/templates/core/pins.html
{% extends "base.html" %}

{% block yield %}
    <div id="pins"></div>
    <div class="spinner"></div>
{% endblock %}

pinry/templates/includes/bookmarklet_link.html
<a id="bookmarklet" href="javascript:void((function(d){var s=d.createElement('script');s.id='pinry-bookmarklet';s.src='http://{{ request.get_host }}/static/js/bookmarklet.js?'+Math.random()*10000000000000000;d.body.appendChild(s)})(document));">Bookmarklet</a>

pinry/templates/includes/field.html
<div class="control-group{% if field.errors %} error{% endif %}">
    <label class="control-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
    <div class="controls">
        {{ field }}
        {% if field.errors %}
            <span class="help-inline">
                {% if field.errors %}
                    {% for error in field.errors %}
                        {{ error|escape }}
                    {% endfor %}
                {% endif %}
            </span>
        {% endif %}
    </div>
</div>

pinry/templates/includes/lightbox.html
{% verbatim %}
    <script id="lightbox-template" type="text/x-handlebars-template">
        <div class="lightbox-background">
            <div class="lightbox-wrapper">
                <div class="lightbox-image-wrapper">
                    <img class="lightbox-image" src="{{image.standard.image}}" />
                </div>
                <div class="lightbox-data clearfix">
                {{#if description}}
                    <div class="description">
                        {{description}}
                    </div>
                {{/if}}
                    <div class="avatar pull-left">
                        <img src="http://gravatar.com/avatar/{{submitter.gravatar}}.jpg">
                    </div>
                    <div class="text pull-left">
                        <span class="dim">pinned by</span> {{submitter.username}}
                        {{#if tags}}
                            <br /><span class="dim">in</span>
                        {{#each tags}}
                            <span class="tag"><a href="/pins/tag/{{this}}/">{{this}}</a></span>
                        {{/each}}
                        {{/if}}
                    </div>
                </div>
            </div>
        </div>
    </script>
{% endverbatim %}

pinry/templates/includes/messages.html
{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}

pinry/templates/includes/pin_form.html
{% verbatim %}
    <script id="pin-form-template" type="text/x-handlebars-template">
        <div class="modal hide fade" id="pin-form">
            <div class="modal-header">
                <h3>New Pin</h3>
            </div>
            <div class="modal-body">
                <div class="span3" id="pin-form-image-preview"></div>
                <div class="span3">
                    <div class="control-group">
                        <label class="control-label" for="pin-form-image-url">Image URL</label>
                        <div class="controls">
                            <input type="text" name="pin-form-image-url" id="pin-form-image-url"/>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="pin-form-image-upload">Image Upload</label>
                        <div class="controls">
                            <div id="pin-form-image-upload"></div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="pin-form-description">Description</label>
                        <div class="controls">
                            <textarea name="pin-form-description" id="pin-form-description"></textarea>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="pin-form-tags">Tags</label>
                        <div class="controls">
                            <input type="text" name="pin-form-tags" id="pin-form-tags"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" id="pin-form-submit">Post</button>
                <button class="btn" id="pin-form-close">Cancel</a>
            </div>
        </div>
    </script>
{% endverbatim %}

pinry/templates/includes/pins.html
{% verbatim %}
    <script id="pins-template" type="text/x-handlebars-template">
        {{#each pins}}
        <div class="pin" data-id="{{id}}">
            {{#if editable}}
                <div class="editable">
                    <div class="borderable">
                        <i class="icon-white icon-trash" data-id="{{id}}"></i>
                    </div>
                    <div class="borderable">
                        <i class="icon-white icon-pencil" data-id="{{id}}"></i>
                    </div>
                </div>
            {{/if}}
            <a href="{{image.standard.image}}" class="lightbox" data-id="{{id}}">
                <div class="image-wrapper" style="width: {{image.thumbnail.width}}px; height: {{image.thumbnail.height}}px;">
                    <img src="{{image.thumbnail.image}}" width="{{image.thumbnail.width}}" height="{{image.thumbnail.height}}"/>
                </div>
            </a>
            {{#if description}}
                <p>{{description}}</p>
            {{/if}}
            <div class="pin-footer clearfix">
                <div class="avatar pull-left">
                    <img src="http://gravatar.com/avatar/{{submitter.gravatar}}">
                </div>
                <div class="text pull-right">
                    <span class="dim">pinned by</span>
                    <a href="/pins/user/{{submitter.username}}/">{{submitter.username}}</a>
                    {{#if tags}}
                        <span class="dim">in</span>
                    {{#each tags}}
                        <span class="tag"><a href="/pins/tag/{{this}}/">{{this}}</a></span>
                    {{/each}}
                    {{/if}}
                </div>
            </div>
        </div>
        {{/each}}
    </script>
{% endverbatim %}

pinry/templates/users/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block yield %}
    <div class="container">
        <div class="row">
            <div id="form" class="span6 offset3">
                <h1>Login</h1>
                <form action="{% url "users:login" %}" method="post" class="form-horizontal">
                    {% csrf_token %}
                    {% for field in form %}
                        {% include "includes/field.html" %}
                    {% endfor %}
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

pinry/templates/users/private.html
{% extends "base.html" %}

{% block title %}Private{% endblock %}

{% block yield %}
    <div class="container">
        <div class="row">
            <div id="form" class="span6 offset3">
                <h1>Private</h1>
                <p>This website is set to private. You need to login before you
                    can view any content.</p>
            </div>
        </div>
    </div>
{% endblock %}

pinry/templates/users/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block yield %}
    <div class="container">
        <div class="row">
            <div id="form" class="span6 offset3">
                <h1>Register</h1>
                <form action="{% url "users:register" %}" method="post" class="form-horizontal">
                    {% csrf_token %}
                    {% for field in form %}
                        {% include "includes/field.html" %}
                    {% endfor %}
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}